---
### -------------------------------------------------
### DIFF CONFIGURATION
### -------------------------------------------------
- name: "DIFF GOLDEN FROM RUNNING ON DEVICE"
  juniper_junos_config:
    load: override
    user: "{{ provider_info.user }}"
    passwd: "{{ provider_info.passwd }}"
    # ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
    src: "{{ build_completed_file }}"
    timeout: 240
    diff: true
    check: false
    commit: false
  register: result

- name: "PRINT THE RESULT TO CONSOLE"
  debug:
    var: result.diff_lines
  when: result.diff_lines is defined
