---
sudo: required

env:
  - distribution: packetferret/ansible-vxlan-evpn-for-campus
    version: 0.0.1

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  # - 'sudo docker build --no-cache --rm --file=files/docker/ansible/Dockerfile --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'docker run -it --rm -v ${PWD}/files/:/home/tmp/files -w /home/tmp/files/ansible/ ${distribution}:${version} ansible-playbook pb.configuration.network.yml --syntax-check'
  - 'docker run -it --rm -v ${PWD}/files/:/home/tmp/files -w /home/tmp/files/ansible/ ${distribution}:${version} ansible-playbook pb.configuration.network.yml'
