---
### ---------------------------------------------------------------------------
### VALIDATE THAT ANSIBLE CONTROL MACHINE IS RUNNING A RECENT ANSIBLE VERSION
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: "Check ansible version >=2.7.8"
      assert:
        msg: "Ansible must be v2.7.8 or higher"
        that:
          - ansible_version.string is version("2.7.8", ">=")
      tags:
        - check
  run_once: True

### ---------------------------------------------------------------------------
### REMOVE AND RECREATE BUILD DIRECTORIES
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  vars_files:
    - "shared/variables.yml"
  roles:
    - { role: localhost-build-dirs }

### ---------------------------------------------------------------------------
### DEBUGGING A HOST
### ---------------------------------------------------------------------------

# - hosts: leaf1
#   connection: local
#   gather_facts: False
#   tasks:
#     - name: "debug all variables"
#       debug:
#         var: "hostvars[inventory_hostname]"

### ---------------------------------------------------------------------------
### BUILD CONFIGURATION IN PIECES AND ASSEMBLE INTO SINGLE CONFIG FILE
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: False
  vars_files:
    - "shared/variables.yml"
    - "shared/secrets.yml"
  roles:
    - { role: juniper_stanza_version }
    - { role: juniper_stanza_apply_groups }
    - { role: juniper_stanza_groups }
    - { role: juniper_stanza_system }
    - {
        role: juniper_stanza_event_options,
        when: "'switch' in device.role",
      }
    - { role: juniper_stanza_chassis }
    - {
        role: juniper_stanza_services,
        when: "'firewall' in device.role",
      }
    - {
        role: juniper_stanza_security,
        when: "'firewall' in device.role",
      }
    - { role: juniper_stanza_interfaces }
    - { role: juniper_stanza_snmp }
    - { role: juniper_stanza_forwarding_options }
    - { role: juniper_stanza_routing_instances }
    - { role: juniper_stanza_routing_options }
    - { role: juniper_stanza_protocols }
    - { role: juniper_stanza_policy_options }
    - { role: juniper_stanza_class_of_service }
    - { role: juniper_stanza_firewall }
    - { role: juniper_stanza_switch_options }
    - { role: juniper_stanza_poe }
    - {
        role: juniper_stanza_virtual_chassis,
        when: "'virtual_chassis' in device.role",
      }
    - { role: juniper_stanza_access }
    - { role: juniper_stanza_vlans }
    - { role: juniper_assemble_config }

### ---------------------------------------------------------------------------
### DEBUGGING A GENERATED CONFIGURATION
### ---------------------------------------------------------------------------

# - hosts: leaf1
#   connection: local
#   gather_facts: False
#   vars_files:
#     - "shared/variables.yml"
#     - "shared/secrets.yml"
#   tasks:
#     - name: display multiple file contents
#       debug: var=item
#       with_file:
#         - "{{ completed_config_file }}"
      

### ---------------------------------------------------------------------------
### VALIDATE, DIFF, AND APPLY CONFIGURATION TO DEVICES
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  vars_files:
    - "shared/variables.yml"
    - "shared/secrets.yml"
  roles:
    # - { role: juniper_configuration_diff }
    # - { role: juniper_configuration_check }
    - { role: juniper_configuration_apply }

