---
- name: "### EXECUTE RPC CALLS ###"
  hosts: spine1
  vars_files:
    - "shared/variables.yml"
    - "shared/secrets.yml"
  roles:
    - juniper.junos
  connection: local
  gather_facts: no
  tasks:
    ### -------------------------------------------------
    ### execute script
    ### -------------------------------------------------
    - name: execute script
      juniper_junos_command:
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"
        timeout: 90
        commands: 
          - show lldp neighbors
      register: cinnamon_tea

    - name: debug
      debug:
        var: cinnamon_tea

