---
- name: "### EXECUTE RPC CALLS ###"
  hosts: leaf1
  vars_files:
    - "shared/variables.yml"
    - "shared/secrets.yml"
  roles:
    - juniper.junos
  connection: local
  gather_facts: no
  tasks:
    ### -------------------------------------------------
    ### GET LLDP neighbors
    ### -------------------------------------------------
    - name: Get LLDP neighbors
      juniper_junos_rpc:
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"
        rpc: get-lldp-neighbors-information
        # kwargs:
        #   table: hoth_geo.inet
        #   extensive: True
      register: cinnamon_tea

    - name: debug
      debug:
        var: cinnamon_tea

