---
all:
  children:
    campus-building-1:
      children:
        core:
          hosts:
            core-sw1:
              ansible_host: "10.6.6.101"
            core-sw2:
              ansible_host: "10.6.6.102"
        access:
          hosts:
            access-sw1:
              ansible_host: "10.6.6.111"
            access-sw2:
              ansible_host: "10.6.6.112"
            access-sw3:
              ansible_host: "10.6.6.113"
            access-sw4:
              ansible_host: "10.6.6.114"
