configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[ae1] connected to access-sw1"
        ether_options:
          ieee_802.3ad:
            bundle: ae1

      - name: xe-0/0/1
        description: "[ae2] connected to access-sw2"
        ether_options:
          ieee_802.3ad:
            bundle: ae2

      - name: xe-0/0/2
        description: "[ae3] connected to access-sw3"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      - name: xe-0/0/10
        description: "[xe-0/0/10] connected to core-sw2"
        mtu: 9100
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.99.0.0/31"

      - name: xe-0/0/11
        description: "[xe-0/0/11] connected to core-sw2"
        mtu: 9100
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.99.0.2/31"

      # ### AE INTERFACES
      - name: ae1
        description: "[xe-0/0/0] connected to access-sw1"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      - name: ae2
        description: "[xe-0/0/1] connected to access-sw2"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      - name: ae3
        description: "[xe-0/0/2] connected to access-sw3"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:03
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      # ### IRB interfaces
      - name: irb
        apply_groups:
          - IRB_OPTIONS
        unit:
          # ### VLAN 1
          - name: "1"
            family:
              inet:
                address:
                  name: "10.0.1.3/24"
                  virtual_gateway_address: "10.0.1.1"
              inet6:
                address:
                  - name: "2001:db8::10:0:1:3/112"
                    virtual_gateway_address: "2001:db8::10:0:1:1"
                  - name: "fe80::10:0:1:3/112"

          # ### VLAN 2
          - name: "2"
            family:
              inet:
                address:
                  name: "10.0.2.3/24"
                  virtual_gateway_address: "10.0.2.1"
              inet6:
                address:
                  - name: "2001:db8::10:0:2:3/112"
                    virtual_gateway_address: "2001:db8::10:0:2:1"
                  - name: "fe80::10:0:2:3/112"

          # ### VLAN 3
          - name: "3"
            family:
              inet:
                address:
                  name: "10.0.3.3/24"
                  virtual_gateway_address: "10.0.3.1"
              inet6:
                address:
                  - name: "2001:db8::10:0:3:3/112"
                    virtual_gateway_address: "2001:db8::10:0:3:1"
                  - name: "fe80::10:0:3:3/112"

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                # arp:
                #   - name: "10.6.5.1"
                #     mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
