configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/1
        description: "Connected to access-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/2
        description: "Connected to access-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/3
        description: "Connected to access-sw3 (member of ae13)"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/0/4
        description: "Connected to access-sw4 (member of ae14)"
        ether_options:
          ieee_802.3ad:
            bundle: ae14

      - name: xe-0/0/9
        mtu: 9100
        unit:
          name: "0"
          description: "Connected to core-sw2"
          family:
            inet:
              address:
                name: "192.168.100.0/31"

      - name: xe-0/0/10
        mtu: 9100
        unit:
          name: "0"
          description: "Connected to core-sw2"
          family:
            inet:
              address:
                name: "192.168.100.2/31"

      - name: xe-0/0/11
        mtu: 9100
        unit:
          name: "0"
          description: "Connected to firewall1"
          family:
            inet:
              address:
                name: "192.168.255.1/31"

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"

      # ### AE INTERFACES
      - name: ae11
        description: "To-Access-1 (members: xe-0/0/1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    "[VLAN-101 VLAN-102 VLAN-201 VLAN-202 VLAN-301 VLAN-302]"

      - name: ae12
        description: "To-Access-2 (members: xe-0/0/2)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:02
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    "[VLAN-101 VLAN-102 VLAN-201 VLAN-202 VLAN-301 VLAN-302]"

      - name: ae13
        description: "To-Access-3 (members: xe-0/0/3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:03
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:03
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    "[VLAN-101 VLAN-102 VLAN-201 VLAN-202 VLAN-301 VLAN-302]"

      - name: ae14
        description: "To-Access-4 (members: xe-0/0/4)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:04
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:04
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    "[VLAN-101 VLAN-102 VLAN-201 VLAN-202 VLAN-301 VLAN-302]"

      # ### IRB INTERFACES
      - name: irb
        apply_groups:
          - IRB_OPTIONS
        unit:
          # ### EMPLOYEE NETWORKS
          - name: "101"
            description: "Wired-Employee"
            family:
              inet:
                address:
                  name: "192.168.101.3/24"
                  virtual_gateway_address: 192.168.101.1

          - name: "102"
            description: "Wireless-Employee"
            family:
              inet:
                address:
                  name: "192.168.102.3/24"
                  virtual_gateway_address: 192.168.102.1

          # ### GUEST NETWORKS
          - name: "201"
            description: "Guest-Wired-Subnet"
            family:
              inet:
                address:
                  name: "192.168.201.3/24"
                  virtual_gateway_address: 192.168.201.1

          - name: "202"
            description: "Guest-Wireless-Subnet"
            family:
              inet:
                address:
                  name: "192.168.202.3/24"
                  virtual_gateway_address: 192.168.202.1

          # ### IOT NETWORKS
          - name: "301"
            description: "Wired-IOT"
            family:
              inet:
                address:
                  name: "192.168.210.3/24"
                  virtual_gateway_address: 192.168.210.1

          - name: "302"
            description: "Wireless-IOT"
            family:
              inet:
                address:
                  name: "192.168.212.3/24"
                  virtual_gateway_address: 192.168.212.1

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
