configuration:
  system:
    host_name: "{{ inventory_hostname }}"
    login:
      user:
        - name: ansible
          authentication:
            encrypted_password: $6$FgsqZPh4$c.DcqHDQLA1gTP0Ok6fC6on30ABVfyJK3F3Y5XKIP8fGu0G0lIWcHiS.sdTNJnGvskywFmEBbZ9Xwo0poRWV90
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUCqloz2uqBHAHv0B8eIRVUDjuGJopQ+R1uVFsYPADeYEnJhlfVxF/jGaTZpK7gHZpaFDhKwm98ouZiwb6fVx0TCKFS4UJTM4qMjdrjzERCFLCyvml/x7YtTmgykHMedxdHJbXeX6FQ7TZ1DHoYPQ8oa1mjeFuj+rY1fa5WIz4Y2rmaukQ+N9OQt4GeaToKFhFtDMKB3zUXJ+TjUaFCIhewqwr8SSTzAdNh87epIUV01/NmRNZK19QXS+ahJfKaZiRExiesfw+qUeO7C/KY9QP5TfDuo6lRy9NfXbll4tOKQFD8BG+TsBzKpp5xjA6dM8wlAx3nORuDZ2P1mt4Y/uQVOckcWN0Kiin7q+o/iAp6yjsOaGtdTLHgBOZNBwD4EeAXO4lPjZR14jzQUKykMx9Y2cB47K4dMi5Co6j+sTBJ0FXCL4sJ7EDKMBYPQk7FcGSza8J9UsBne64C+iAzGN+mUlYRNqj3qIjtY/vRpSrnKbyzDABr7Xz+CgsvqYTowGU7RuW723JFpA2WlBM9XYz4rJFuHTERzQUH9V/Y+jze05BpW7x+52LuKrTMmMR6Ykje4bo4fryCsf4w/jgSdq08Yt3Qd7j73C0IxYXpE5Ib57sN+qoKVVuMhVhXrTtZDJwtIGopKK2z8YmIqvIDUOlcK+IYWwpf2xWEDMMOZnkzw== ansible awx tower ssh keys
          class: super-user
          uid: "3000"
        - name: nornir
          authentication:
            encrypted_password: $6$DCyoMC6o$8NzXXdAIX4pD93DMgfO/2gyltgXhqFbngkYTGhksksLIbJuvGjXn8IcQQahRBXkkBUWJgbGb9mweZikl1bzAX1
          class: super-user
          uid: "3001"
        - name: packetferret
          authentication:
            encrypted_password: $6$s8L/YliX$0uji4ZNG4mUt59noVjvyd9NlcpKx88h5BN3sqeHoAGaDsfyJMqsNFGUs.LGhvyT1iP3faYNA1CTqxxTQ0MQRW1
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWRvTNMu/WTbpowURuKduMBaARWfNoyyXXJxbpt/h6QOd8wYx5Mt1YeoCvdUVFHgmFFxXJc6cmV3Oe8IHReF8NEgW1x2MA+Eg/M6GmKmWVUaJvlUO0raggwsWFk1YQkDIn+qaO46lDEuz0hhpR9INKQ30M6W/3DRojDfVNH9XjpFGB7KCnfA0GHvNGyEakwu7WvfqQWO2D0hPg85SCu9bsuifpLa1qm4FPIqqQqIN0AMlNOdaGnVIE5vqnTsmqi6T18R0qXLPs2vtXbpKR7s2awelVDZovwrQABDah87TCpudyrFWOR00sA/+q9uOVBR9gNnHCjX9lw5exhp71Yq8kmcgpzo9ejevShFUQrGVoist8wwXDI0BJyfqxFMLIKLc8wVHT309y6Lj0jxtfyd98Ngiv3wMCi80AcpukJDLVco6QNrqBk5KPin/2XFoIpSWmkTrOh5nFgHL4HrUAiOmvV3h60WaO6SxkcHp7x8fnt/YnfzXB90Hiy8b/dqi5wFEeRAgKnGo97LvFxbM8UfKOZKVB9cKSqXaloL9Fke56HwTIGFPFMXccOxjfsDdlpHJ7PiPbwq4X6z4VyY3Tyo8c5sxcaKHRX8IQtzId/pn2JvoUVGdiF6G9ZoYbgCGYeWsjczxE4Y/PJwoMm1W5dU47F58BKh/im+i52bmdC1sIvw== apple-pc-01.redtail.local
          class: super-user
          uid: "3002"
    name_server:
      - name: 10.255.127.250
      - name: 10.255.127.251
    root_authentication:
      encrypted_password: $6$eG4FXiQW$J4/a.5GZlXlrKcvJTpbaMl.qIelPqjR5lFk.POmxo5O3Vp5OdjHFFJ97PMqvABuZZOGXrdvSE6YF3f33wilgO.
      ssh_rsa:
        name: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    services:
      netconf:
        ssh: null
      rest:
        enable_explorer: null
        http:
          port: "8080"
      ssh:
        root_login: allow
    syslog:
      file:
        - name: messages
          contents:
            - name: any
              notice: null

            - name: authorization
              info: null

        - name: interactive-commands
          contents:
            any: null
            name: interactive-commands

        - name: default-log-messages
          match: "(requested 'commit' operation)|(requested 'commit synchronize' operation)|(copying configuration to juniper.save)|(commit complete)|ifAdminStatus|(FRU power)|(FRU removal)|(FRU insertion)|(link UP)|transitioned|Transferred|transfer-file|(license add)|(license delete)|(package -X update)|(package -X delete)|(FRU Online)|(FRU Offline)|(plugged in)|(unplugged)|GRES"
          contents:
            info: null
            name: any
          structured_data: null

      host:
        - name: 10.255.127.15
          contents:
            any: null
            name: any
          source_address: "{{ ansible_host }}"

      user:
        contents:
          emergency: null
          name: any
        name: "*"
        # match: "!(.*Scheduler Oinker*.|.*Frame 0*.|.*ms without yielding*.)"
    time_zone: America/Chicago
