---
- name: check if directory is present
  file: path={{ configuration_directory }} state=directory
  run_once: true

- name: assemble configurations and copy to configuration
  assemble: src={{ build_directory }} dest={{ completed_config_file }}

- name: Remove blank lines between matches
  lineinfile:
    path: "{{ completed_config_file }}"
    regexp: '(^\s*$)'
    state: absent
