configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        mtu: 9100
        unit:
          name: "0"
          description: "Connected to iot-pc-1"
          family:
            ethernet_switching:
              interface_mode: access
              vlan:
                members: "vlan_3"

      - name: xe-0/0/8
        description: "Connected to dist-sw3 (member of ae3)"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      - name: xe-0/0/9
        description: "Connected to dist-sw3 (member of ae3)"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      - name: xe-0/0/10
        description: "Connected to dist-sw4 (member of ae3)"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      - name: xe-0/0/11
        description: "Connected to dist-sw4 (member of ae3)"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      # ### AE INTERFACES
      - name: ae3
        description: "To-Distribution-3-4 (members: xe-0/0/8-11)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                arp:
                  - name: "10.6.5.1"
                    mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
