configuration:
  routing_instances:
    instance:

      # ### VRF 1: Guest Access
      - name: "JNPR_1_VRF"
        description: "VRF for Employee Access"
        instance_type: "vrf"
        interface:
          # ### PHYSICAL INTERFACES
          # ### LOOPBACK INTERFACES
          - name: "lo0.1"
          # ### VLAN GATEWAY INTERFACES
          - name: "irb.1"
        route_distinguisher:
          rd_type: "{{ device.lo0.ipv4 }}:1"
        routing_options:
          auto_export:
            family:
              inet:
                unicast:
                  - null
          static:
            route:
              - name: "0.0.0.0/0"
                next_hop:
                  - "10.1.1.1"
        vrf_table_label: null
        vrf_target: 
          community: "target:1:65001"

      # ### VRF 2: Employee Access
      - name: "JNPR_2_VRF"
        description: "VRF for Guest Access"
        instance_type: "vrf"
        interface:
          # ### PHYSICAL INTERFACES
          # ### LOOPBACK INTERFACES
          - name: "lo0.2"
          # ### VLAN GATEWAY INTERFACES
          - name: "irb.2"
        route_distinguisher:
          rd_type: "{{ device.lo0.ipv4 }}:2"
        routing_options:
          auto_export:
            family:
              inet:
                unicast:
                  - null
          static:
            route:
              - name: "0.0.0.0/0"
                next_hop:
                  - "10.1.2.1"
        vrf_table_label: null
        vrf_target: 
          community: "target:2:65001"

      # ### VRF 3: IOT Access
      - name: "JNPR_3_VRF"
        description: "VRF for IOT Access"
        instance_type: "vrf"
        interface:
          # ### PHYSICAL INTERFACES
          # ### LOOPBACK INTERFACES
          - name: "lo0.3"
          # ### VLAN GATEWAY INTERFACES
          - name: "irb.3"
        route_distinguisher:
          rd_type: "{{ device.lo0.ipv4 }}:3"
        routing_options:
          auto_export:
            family:
              inet:
                unicast:
                  - null
          static:
            route:
              - name: "0.0.0.0/0"
                next_hop:
                  - "10.1.3.1"
        vrf_table_label: null
        vrf_target: 
          community: "target:3:65001"