configuration:
  routing_options:
    forwarding_table:
      export: 
        - "POLICY_LB"
      ecmp_fast_reroute: 
        - null
    router_id: "{{ device.lo0.ipv4 }}"
    autonomous_system:
      as_number: "65100"
