configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "Connected to campus-rt1 (member of ae16)"
        ether_options:
          ieee_802.3ad:
            bundle: ae16

      - name: xe-0/0/1
        description: "Connected to campus-rt1 (member of ae16)"
        ether_options:
          ieee_802.3ad:
            bundle: ae16

      - name: xe-0/0/2
        description: "Connected to dist-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/3
        description: "Connected to dist-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/4
        description: "Connected to dist-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/5
        description: "Connected to dist-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/6
        description: "Connected to dist-sw3 (member of ae13)"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/0/7
        description: "Connected to dist-sw3 (member of ae13)"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/0/8
        description: "Connected to dist-sw4 (member of ae14)"
        ether_options:
          ieee_802.3ad:
            bundle: ae14

      - name: xe-0/0/9
        description: "Connected to dist-sw4 (member of ae14)"
        ether_options:
          ieee_802.3ad:
            bundle: ae14

      - name: xe-0/0/10
        description: "Connected to campus-fw1 (member of ae15)"
        ether_options:
          ieee_802.3ad:
            bundle: ae15

      - name: xe-0/0/11
        description: "Connected to campus-fw1 (member of ae15)"
        ether_options:
          ieee_802.3ad:
            bundle: ae15

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to dist-sw1 (members: xe-0/0/2-3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.0/31"

      - name: ae12
        description: "Connected to dist-sw2 (members: xe-0/0/4-5)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.2/31"

      - name: ae13
        description: "Connected to dist-sw3 (members: xe-0/0/6-7)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.4/31"

      - name: ae14
        description: "Connected to dist-sw4 (members: xe-0/0/8-9)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.6/31"

      - name: ae15
        description: "Connected to campus-fw1 (members: xe-0/0/10-11)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      - name: ae16
        description: "Connected to campus-rt1 (members: xe-0/0/0-1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.20.1/31"

      # ### IRB interfaces
      - name: irb
        unit:

          # ### VLAN 1
          - name: "1"
            family:
              inet:
                address:
                  name: "172.20.1.252/24"
                  virtual_gateway_address: "172.20.1.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:1:252/112"
                    virtual_gateway_address: "2001:db8::172:20:1:250"
                  - name: "fe80::172:20:1:252/112"

          # ### VLAN 2
          - name: "2"
            family:
              inet:
                address:
                  name: "172.20.2.252/24"
                  virtual_gateway_address: "172.20.2.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:2:252/112"
                    virtual_gateway_address: "2001:db8::172:20:2:250"
                  - name: "fe80::172:20:2:252/112"

          # ### VLAN 3
          - name: "3"
            family:
              inet:
                address:
                  name: "172.20.3.252/24"
                  virtual_gateway_address: "172.20.3.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:3:252/112"
                    virtual_gateway_address: "2001:db8::172:20:3:250"
                  - name: "fe80::172:20:3:252/112"

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                arp:
                  - name: "10.6.5.1"
                    mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"

          - name: "1"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo1.ipv4 }}/32"

