configuration:
  protocols:
    bgp:
      group:

        # ### UNDERLAY
        - name: "UNDERLAY"
          family:
            inet:
              unicast: null
          multipath: null
          neighbor:
            - description: "core-sw1"
              name: 192.168.100.0
            - description: "core-sw1"
              name: 192.168.100.2
          local_as: 
            as_number: 65012
          peer_as: 65011
          import: UNDERLAY-IMPORT
          export: UNDERLAY-EXPORT
          type: external

        # ### OVERLAY
        - name: "EVPN_FABRIC"
          family:
            evpn:
              signaling: null
          local_address: "{{ device.lo0.ipv4 }}"
          multipath: null
          neighbor:
            - description: "core-sw1"
              name: 192.168.255.11
          type: internal

    evpn:
      encapsulation: "vxlan"
      default_gateway: "no-gateway-community"
      extended_vni_list:
        - "5101"
        - "5102"
        - "5201"
        - "5202"
        - "5301"
        - "5302"

    igmp_snooping:
      vlan:
        - name: "VLAN-201"
          interface: "ae11.0"
          multicast_router_interface: null
