configuration:
  protocols:
    bgp:
      group:
        - name: "LEAF_EVPN_OVERLAY"
          family:
            evpn:
              signaling: null
          local_address: "{{ device.lo0.ipv4 }}"
          multipath: null
          neighbor:
            - description: "spine1"
              name: 192.168.200.1
            - description: "spine2"
              name: 192.168.200.2
          type: internal
    evpn:
      encapsulation: "vxlan"
      # default_gateway: "no-gateway-community"
      extended_vni_list:
        - "all"
