configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: ge-0/0/6
        description: "Connected to campus-tme-ex2300-01 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: ge-0/0/46
        unit:
          name: "0"
          description: "Connected to campus-tme-ex4650-01"
          family:
            inet:
              address:
                name: "192.168.100.4/31"

      # ### AE INTERFACES
      - name: ae11
        description: "To-Access-1 (members: ge-0/0/6)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    [VLAN-201 VLAN-202 VLAN-101 VLAN-102 VLAN-301 VLAN-302]

      - name: ae12
        description: "To-Access-2 (members: ge-0/0/2)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:02
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    [VLAN-201 VLAN-202 VLAN-101 VLAN-102 VLAN-301 VLAN-302]

      # ### IRB INTERFACES
      - name: irb
        apply_groups:
          - IRB_OPTIONS
        unit:
          - name: "101"
            description: "Wired-Employee"
            family:
              inet:
                address:
                  name: "192.168.101.2/24"
                  virtual_gateway_address: 192.168.101.1
          - name: "102"
            description: "Wireless-Employee"
            family:
              inet:
                address:
                  name: "192.168.102.2/24"
                  virtual_gateway_address: 192.168.102.1
          - name: "201"
            description: "Guest-Wired-Subnet"
            family:
              inet:
                address:
                  name: "192.168.201.2/24"
                  virtual_gateway_address: 192.168.201.1
          - name: "202"
            description: "Guest-Wireless-Subnet"
            family:
              inet:
                address:
                  name: "192.168.202.2/24"
                  virtual_gateway_address: 192.168.202.1
          - name: "301"
            description: "Wired-IOT"
            family:
              inet:
                address:
                  name: "192.168.210.2/24"
                  virtual_gateway_address: 192.168.210.1
          - name: "302"
            description: "Wireless-IOT"
            family:
              inet:
                address:
                  name: "192.168.212.2/24"
                  virtual_gateway_address: 192.168.212.1

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
              iso:
                address:
                  name: "{{ device.lo0.iso }}"
