configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/2
        description: "Connected to core-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/3
        description: "Connected to core-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/4
        description: "Connected to core-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/5
        description: "Connected to core-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/6
        description: "Connected to access-sw1 (member of ae21)"
        ether_options:
          ieee_802.3ad:
            bundle: ae21

      - name: xe-0/0/7
        description: "Connected to access-sw1 (member of ae21)"
        ether_options:
          ieee_802.3ad:
            bundle: ae21

      - name: xe-0/0/8
        description: "Connected to access-sw2 (member of ae22)"
        ether_options:
          ieee_802.3ad:
            bundle: ae22

      - name: xe-0/0/9
        description: "Connected to access-sw2 (member of ae22)"
        ether_options:
          ieee_802.3ad:
            bundle: ae22

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to core-sw1 (members: xe-0/0/2-3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.1.3/31"

      - name: ae12
        description: "Connected to core-sw2 (members: xe-0/0/4-5)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.3/31"

      - name: ae21
        description: "Connected to access-sw1 (members: xe-0/0/6-7)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      - name: ae22
        description: "Connected to access-sw2 (members: xe-0/0/8-9)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:02
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                arp:
                  - name: "10.6.5.1"
                    mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
