configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[ae0] connection to core-sw1: xe-0/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae0

      - name: xe-0/0/1
        description: "[ae0] connection to core-sw2: xe-0/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae0

      - name: xe-0/0/2
        mtu: 9100
        unit:
          name: "0"
          description: "[xe-0/0/2] connection to mist-ap1: eth0"
          family:
            ethernet_switching:
              interface_mode: trunk
              vlan:
                members: "all"

      - name: xe-0/0/3
        mtu: 9100
        unit:
          name: "0"
          description: "[xe-0/0/3] connection to mist-ap2: eth0"
          family:
            ethernet_switching:
              interface_mode: access
              vlan:
                members: "vlan_1"

      # ### AE INTERFACES
      - name: ae0
        description: "[xe-0/0/0-1] connection to core layer"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1
                    - vlan_2
                    - vlan_3

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                # arp:
                #   - name: "10.6.5.1"
                #     mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      # - name: lo0
      #   unit:
      #     - name: "0"
      #       description: loopback
      #       family:
      #         inet:
      #           address:
      #             name: "{{ device.lo0.ipv4 }}/32"
